export const styles: string = `
:host{all:initial;position:fixed;inset:0;pointer-events:none!important;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#253047;line-height:1.4;--bg:#fff;--ink:#253047;--muted:#66758a;--line:#dce2ed;--accent:#4869d8;--soft:#eef2ff;--peer:#f4f6fa;--error:#b82f40;--shadow:0 8px 32px #17223a24;--orb-bg:#fffffff0;--orb-halo:#728be05c;--orb-shadow:#17223a38}
*,*::before,*::after{box-sizing:border-box}button,select{font:inherit}button{cursor:pointer;touch-action:manipulation}button:disabled{cursor:default;opacity:.4}button:focus-visible,select:focus-visible{outline:2px solid var(--accent);outline-offset:2px}button{border:0;color:var(--ink);background:transparent}button:hover:not(:disabled){background:var(--soft)}[hidden]{display:none!important}
.launcher-group{pointer-events:none;position:absolute;width:48px;height:48px;z-index:2}.launcher,.feature-button{pointer-events:auto;position:absolute;display:grid;place-items:center;border-radius:50%;color:var(--accent)}.launcher{inset:0;width:48px;height:48px;isolation:isolate;overflow:visible;background:var(--orb-bg);border:1px solid #ffffffb8;box-shadow:0 10px 26px var(--orb-shadow),0 2px 8px #17223a24,inset 0 1px 1px #fff;touch-action:none;backdrop-filter:blur(12px);transition:transform .18s ease,background .18s ease,box-shadow .18s ease}.launcher::before,.launcher::after{content:"";position:absolute;pointer-events:none;border-radius:50%;z-index:-1}.launcher::before{inset:-6px;background:radial-gradient(circle,var(--orb-halo) 0 48%,transparent 72%);filter:blur(7px);opacity:.7}.launcher::after{inset:-3px;border:1px solid var(--orb-halo);filter:blur(2px);opacity:.65}.launcher svg{width:20px;height:20px;pointer-events:none}.launcher:hover{background:var(--soft);transform:translateY(-1px);box-shadow:0 13px 30px var(--orb-shadow),0 3px 9px #17223a24,inset 0 1px 1px #fff}.launcher[aria-expanded=true]{background:var(--soft);box-shadow:0 12px 30px var(--orb-shadow),0 0 0 4px var(--orb-halo)}
.feature-menu{position:absolute;inset:0}.feature-button{left:4px;top:4px;width:40px;height:40px;visibility:hidden;opacity:0;background:var(--orb-bg);border:1px solid var(--line);box-shadow:0 7px 18px var(--orb-shadow),inset 0 1px 1px #fff;transform:translate(0,0) scale(.42);transition:transform .2s cubic-bezier(.2,.8,.2,1),opacity .15s ease,visibility 0s linear .2s;will-change:transform,opacity}.feature-button svg{width:20px;height:20px;pointer-events:none}.feature-button[aria-disabled=true]{color:var(--muted);cursor:default;opacity:0}.launcher-group[data-quadrant=bottom-right] .feature-button:nth-child(1){--feature-x:-64px;--feature-y:0px}.launcher-group[data-quadrant=bottom-right] .feature-button:nth-child(2){--feature-x:-48px;--feature-y:-48px}.launcher-group[data-quadrant=bottom-right] .feature-button:nth-child(3){--feature-x:0px;--feature-y:-64px}.launcher-group[data-quadrant=bottom-left] .feature-button:nth-child(1){--feature-x:0px;--feature-y:-64px}.launcher-group[data-quadrant=bottom-left] .feature-button:nth-child(2){--feature-x:48px;--feature-y:-48px}.launcher-group[data-quadrant=bottom-left] .feature-button:nth-child(3){--feature-x:64px;--feature-y:0px}.launcher-group[data-quadrant=top-left] .feature-button:nth-child(1){--feature-x:64px;--feature-y:0px}.launcher-group[data-quadrant=top-left] .feature-button:nth-child(2){--feature-x:48px;--feature-y:48px}.launcher-group[data-quadrant=top-left] .feature-button:nth-child(3){--feature-x:0px;--feature-y:64px}.launcher-group[data-quadrant=top-right] .feature-button:nth-child(1){--feature-x:0px;--feature-y:64px}.launcher-group[data-quadrant=top-right] .feature-button:nth-child(2){--feature-x:-48px;--feature-y:48px}.launcher-group[data-quadrant=top-right] .feature-button:nth-child(3){--feature-x:-64px;--feature-y:0px}.launcher-group[data-menu-open=true] .feature-button{visibility:visible;opacity:1;pointer-events:auto;transform:translate(var(--feature-x),var(--feature-y)) scale(1);transition-delay:0s}.launcher-group[data-menu-open=true] .feature-button[aria-disabled=true]{opacity:.58}.launcher-group[data-menu-open=true] .feature-button:nth-child(2){transition-delay:45ms}.launcher-group[data-menu-open=true] .feature-button:nth-child(3){transition-delay:90ms}.feature-button:hover:not([aria-disabled=true]){background:var(--soft);transform:translate(var(--feature-x),var(--feature-y)) scale(1.06)}.launcher-status{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.panel{pointer-events:auto;position:absolute;width:min(340px,calc(100vw - 24px));max-height:calc(100dvh - 24px - env(safe-area-inset-bottom));overflow:auto;overscroll-behavior:contain;background:var(--bg);color:var(--ink);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);padding:14px;font-size:12px}
.header{display:flex;align-items:center;gap:6px;margin-bottom:8px}.title{font-size:14px;font-weight:650;flex:1;touch-action:none;cursor:grab;user-select:none}.icon-button{width:32px;height:32px;border-radius:8px;font-size:17px;display:grid;place-items:center}.difficulty{max-width:78px;border:0;border-radius:6px;background:var(--peer);color:var(--ink);padding:6px;font-size:12px}.status{display:flex;justify-content:space-between;margin:0 1px 10px;color:var(--muted);font-variant-numeric:tabular-nums}.clock{color:var(--ink)}
.board-wrap{position:relative}.board{border:2px solid var(--ink);border-radius:3px;overflow:hidden;width:100%;aspect-ratio:1;background:var(--line);display:flex;flex-direction:column}.row{display:grid;grid-template-columns:repeat(9,1fr);flex:1;min-height:0}.cell{border-radius:0;position:relative;min-width:0;padding:0;background:var(--bg);border-right:1px solid var(--line);border-bottom:1px solid var(--line);display:grid;place-items:center;font-size:21px;font-variant-numeric:tabular-nums;color:var(--accent);font-weight:450}.cell:nth-child(3n){border-right:2px solid var(--ink)}.cell:nth-child(9){border-right:0}.row:nth-child(3n) .cell{border-bottom:2px solid var(--ink)}.row:last-child .cell{border-bottom:0}.cell.given{color:var(--ink);font-weight:650}.cell.peer{background:var(--peer)}.cell.same{background:var(--soft)}.cell.selected{background:#dce5ff;box-shadow:inset 0 0 0 2px var(--accent);z-index:1}.cell.error{color:var(--error);text-decoration:underline;text-decoration-style:dotted}.cell.hint{box-shadow:inset 0 0 0 2px #ba861c}.cell .notes{display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(3,1fr);position:absolute;inset:1px;font-size:8px;color:var(--muted);line-height:1}.notes span{display:grid;place-items:center}.pause-screen{position:absolute;inset:0;display:grid;place-items:center;background:var(--bg);border:2px solid var(--ink);border-radius:3px}.resume{padding:12px 20px;border-radius:10px;background:var(--soft);color:var(--accent);font-size:14px}.digits{display:grid;grid-template-columns:repeat(9,1fr);margin:9px 0 5px;gap:2px}.digit{height:40px;color:var(--accent);font-size:22px;border-radius:7px}.toolbar{display:grid;grid-template-columns:repeat(4,1fr);gap:3px}.tool{height:36px;border-radius:7px;color:var(--muted);font-size:12px}.tool[aria-pressed=true]{background:var(--soft);color:var(--accent)}.footer{display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line);margin-top:9px;padding-top:8px}.footer button{height:32px;padding:0 8px;border-radius:7px}.new-game{color:var(--accent)}
.notice:empty{display:none}.notice{color:var(--muted);font-size:11px;margin:8px 1px 0}.dialog{margin-top:10px;padding:12px;border-radius:10px;background:var(--peer)}.dialog p{margin:0 0 8px;line-height:1.6}.dialog .actions{display:flex;gap:6px;justify-content:flex-end}.dialog button{border-radius:6px;padding:7px 10px}.primary{background:var(--accent)!important;color:#fff!important}.settings-row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:9px 0}.settings-row input{accent-color:var(--accent)}.settings-row select{background:var(--bg);color:var(--ink);border:1px solid var(--line);border-radius:5px;padding:4px}.won{color:var(--accent);font-weight:600}.panel[data-paused=true] .board{visibility:hidden}
:host([data-theme=dark]){--bg:#20252e;--ink:#e3e8f2;--muted:#9ba7bb;--line:#39414f;--accent:#99afff;--soft:#303c5a;--peer:#282f3a;--error:#ff8995;--shadow:0 8px 32px #0006;--orb-bg:#20252ef0;--orb-halo:#8099ff5c;--orb-shadow:#0009}:host([data-theme=dark]) .cell.selected{background:#3c4d76}
@media(prefers-color-scheme:dark){:host([data-theme=system]){--bg:#20252e;--ink:#e3e8f2;--muted:#9ba7bb;--line:#39414f;--accent:#99afff;--soft:#303c5a;--peer:#282f3a;--error:#ff8995;--shadow:0 8px 32px #0006;--orb-bg:#20252ef0;--orb-halo:#8099ff5c;--orb-shadow:#0009}:host([data-theme=system]) .cell.selected{background:#3c4d76}}
@media(prefers-reduced-motion:reduce){.launcher,.feature-button{transition-duration:.01ms!important;transition-delay:0s!important}}
@media(max-width:400px){.panel{padding:12px}.tool{height:40px}.title{cursor:default}}
.g-stat{color:var(--muted);font-size:10px;white-space:nowrap}.g-stat b{color:var(--ink);font-size:13px;font-variant-numeric:tabular-nums}
.g-board{position:relative;box-sizing:border-box;width:100%;aspect-ratio:1;padding:var(--g-pad);--g-pad:8px;--g-gap:8px;background:var(--peer);border:1px solid var(--line);border-radius:10px}
.g-board:focus-visible,.g-stick-base:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
.g-cells{position:absolute;inset:var(--g-pad);display:grid;grid-template-columns:repeat(4,1fr);grid-template-rows:repeat(4,1fr);gap:var(--g-gap)}
.g-cells span{background:var(--g-cell,#dde3ee);border-radius:7px}
.g-tiles{position:absolute;inset:var(--g-pad);pointer-events:none}
.g-tile{position:absolute;left:0;top:0;width:calc((100% - 3 * var(--g-gap)) / 4);aspect-ratio:1;display:grid;place-items:center;border-radius:7px;font-weight:700;font-size:22px;font-variant-numeric:tabular-nums;--g-bg:#eee4da;--g-ink:#776e65;background:var(--g-bg);color:var(--g-ink);transform:translate(calc(var(--g-col) * (100% + var(--g-gap))),calc(var(--g-row) * (100% + var(--g-gap))));transition:transform .12s ease-out}
.g-tile[data-value="4"]{--g-bg:#ede0c8}
.g-tile[data-value="8"]{--g-bg:#f2b179;--g-ink:#fff}
.g-tile[data-value="16"]{--g-bg:#f59563;--g-ink:#fff}
.g-tile[data-value="32"]{--g-bg:#f67c5f;--g-ink:#fff}
.g-tile[data-value="64"]{--g-bg:#f65e3b;--g-ink:#fff}
.g-tile[data-value="128"]{--g-bg:#edcf72;--g-ink:#fff}
.g-tile[data-value="256"]{--g-bg:#edcc61;--g-ink:#fff}
.g-tile[data-value="512"]{--g-bg:#edc850;--g-ink:#fff}
.g-tile[data-value="1024"]{--g-bg:#edc53f;--g-ink:#fff;font-size:19px}
.g-tile[data-value="2048"]{--g-bg:#edc22e;--g-ink:#fff;font-size:19px}
.g-tile[data-big=true]{--g-bg:#3c3a32;--g-ink:#fff;font-size:19px}
.g-tile.is-new{animation:g-new .16s ease-out}
.g-tile.is-merged{animation:g-merge .22s ease-out}
@keyframes g-new{from{opacity:0}to{opacity:1}}
@keyframes g-merge{0%{box-shadow:0 0 0 3px var(--accent)}100%{box-shadow:0 0 0 0 transparent}}
.g-stick{display:grid;place-items:center;margin:10px 0 2px;touch-action:none}
.g-stick-base{position:relative;display:grid;place-items:center;width:74px;height:74px;border-radius:50%;background:var(--peer);border:1px solid var(--line);cursor:grab;touch-action:none;user-select:none;-webkit-user-select:none}
.g-stick[data-active=true] .g-stick-base{cursor:grabbing;border-color:var(--accent)}
.g-stick-knob{width:34px;height:34px;border-radius:50%;background:var(--orb-bg);border:1px solid var(--line);box-shadow:0 4px 12px var(--orb-shadow);transition:transform .12s ease-out;pointer-events:none}
.g-stick[data-active=true] .g-stick-knob{transition:none}
.g-tip{color:var(--muted);font-size:10px}
:host([data-theme=dark]) .g-cells span{background:#2a313c}:host([data-theme=dark]) .g-tile{--g-bg:#3a4150;--g-ink:#e3e8f2}:host([data-theme=dark]) .g-tile[data-value="4"]{--g-bg:#434b5c}
@media(prefers-color-scheme:dark){:host([data-theme=system]) .g-cells span{background:#2a313c}:host([data-theme=system]) .g-tile{--g-bg:#3a4150;--g-ink:#e3e8f2}:host([data-theme=system]) .g-tile[data-value="4"]{--g-bg:#434b5c}}
@media(prefers-reduced-motion:reduce){.g-tile{transition-duration:.01ms}.g-tile.is-new,.g-tile.is-merged{animation:none}}
`;
