export const styles: string = `
:host{all:initial;position:fixed;inset:0;pointer-events:none!important;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#253047;line-height:1.4;--bg:#fff;--ink:#253047;--muted:#66758a;--line:#dce2ed;--accent:#4869d8;--soft:#eef2ff;--peer:#f4f6fa;--error:#b82f40;--shadow:0 8px 32px #17223a24}
*,*::before,*::after{box-sizing:border-box}button,select{font:inherit}button{cursor:pointer;touch-action:manipulation}button:disabled{cursor:default;opacity:.4}button:focus-visible,select:focus-visible{outline:2px solid var(--accent);outline-offset:2px}button{border:0;color:var(--ink);background:transparent}button:hover:not(:disabled){background:var(--soft)}[hidden]{display:none!important}
.launcher{pointer-events:auto;position:absolute;width:40px;height:40px;display:grid;place-items:center;background:var(--bg);border:1px solid var(--line);border-radius:13px;box-shadow:0 3px 12px #17223a18;touch-action:none;color:var(--accent)}.launcher svg{width:22px;height:22px;pointer-events:none}.launcher[aria-expanded=true]{background:var(--soft)}
.panel{pointer-events:auto;position:absolute;width:min(340px,calc(100vw - 24px));max-height:calc(100dvh - 24px - env(safe-area-inset-bottom));overflow:auto;overscroll-behavior:contain;background:var(--bg);color:var(--ink);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);padding:14px;font-size:12px}
.header{display:flex;align-items:center;gap:6px;margin-bottom:8px}.title{font-size:14px;font-weight:650;flex:1;touch-action:none;cursor:grab;user-select:none}.icon-button{width:32px;height:32px;border-radius:8px;font-size:17px;display:grid;place-items:center}.difficulty{max-width:78px;border:0;border-radius:6px;background:var(--peer);color:var(--ink);padding:6px;font-size:12px}.status{display:flex;justify-content:space-between;margin:0 1px 10px;color:var(--muted);font-variant-numeric:tabular-nums}.clock{color:var(--ink)}
.board-wrap{position:relative}.board{border:2px solid var(--ink);border-radius:3px;overflow:hidden;width:100%;aspect-ratio:1;background:var(--line);display:flex;flex-direction:column}.row{display:grid;grid-template-columns:repeat(9,1fr);flex:1;min-height:0}.cell{border-radius:0;position:relative;min-width:0;padding:0;background:var(--bg);border-right:1px solid var(--line);border-bottom:1px solid var(--line);display:grid;place-items:center;font-size:21px;font-variant-numeric:tabular-nums;color:var(--accent);font-weight:450}.cell:nth-child(3n){border-right:2px solid var(--ink)}.cell:nth-child(9){border-right:0}.row:nth-child(3n) .cell{border-bottom:2px solid var(--ink)}.row:last-child .cell{border-bottom:0}.cell.given{color:var(--ink);font-weight:650}.cell.peer{background:var(--peer)}.cell.same{background:var(--soft)}.cell.selected{background:#dce5ff;box-shadow:inset 0 0 0 2px var(--accent);z-index:1}.cell.error{color:var(--error);text-decoration:underline;text-decoration-style:dotted}.cell.hint{box-shadow:inset 0 0 0 2px #ba861c}.cell .notes{display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(3,1fr);position:absolute;inset:1px;font-size:8px;color:var(--muted);line-height:1}.notes span{display:grid;place-items:center}.pause-screen{position:absolute;inset:0;display:grid;place-items:center;background:var(--bg);border:2px solid var(--ink);border-radius:3px}.resume{padding:12px 20px;border-radius:10px;background:var(--soft);color:var(--accent);font-size:14px}.digits{display:grid;grid-template-columns:repeat(9,1fr);margin:9px 0 5px;gap:2px}.digit{height:40px;color:var(--accent);font-size:22px;border-radius:7px}.toolbar{display:grid;grid-template-columns:repeat(4,1fr);gap:3px}.tool{height:36px;border-radius:7px;color:var(--muted);font-size:12px}.tool[aria-pressed=true]{background:var(--soft);color:var(--accent)}.footer{display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line);margin-top:9px;padding-top:8px}.footer button{height:32px;padding:0 8px;border-radius:7px}.new-game{color:var(--accent)}
.notice:empty{display:none}.notice{color:var(--muted);font-size:11px;margin:8px 1px 0}.dialog{margin-top:10px;padding:12px;border-radius:10px;background:var(--peer)}.dialog p{margin:0 0 8px;line-height:1.6}.dialog .actions{display:flex;gap:6px;justify-content:flex-end}.dialog button{border-radius:6px;padding:7px 10px}.primary{background:var(--accent)!important;color:#fff!important}.settings-row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:9px 0}.settings-row input{accent-color:var(--accent)}.settings-row select{background:var(--bg);color:var(--ink);border:1px solid var(--line);border-radius:5px;padding:4px}.won{color:var(--accent);font-weight:600}.panel[data-paused=true] .board{visibility:hidden}
:host([data-theme=dark]){--bg:#20252e;--ink:#e3e8f2;--muted:#9ba7bb;--line:#39414f;--accent:#99afff;--soft:#303c5a;--peer:#282f3a;--error:#ff8995;--shadow:0 8px 32px #0006}:host([data-theme=dark]) .cell.selected{background:#3c4d76}
@media(prefers-color-scheme:dark){:host([data-theme=system]){--bg:#20252e;--ink:#e3e8f2;--muted:#9ba7bb;--line:#39414f;--accent:#99afff;--soft:#303c5a;--peer:#282f3a;--error:#ff8995;--shadow:0 8px 32px #0006}:host([data-theme=system]) .cell.selected{background:#3c4d76}}
@media(max-width:400px){.panel{padding:12px}.tool{height:40px}.title{cursor:default}}
`;
